webserver/main/urls.py
from django.urls import include, path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('help', views.help, name='help'),
    path('details/<int:pk>/', views.details, name="details"),
    path('overview', views.overview, name='overview'),
    path('tools', views.publications, name='publications'),
    path('tool/<int:pk>/', views.publication, name='publication'),
    path('register', views.author, name='author'),
    path('paperData', views.paperData, name='paperData'),
    path('websiteData', views.websiteData, name='websiteData'),
    path('statistics', views.statistics, name='statistics'),
    path("table_data", view=views.Table.as_view(), name='table_data'),
    path("curated_data", view=views.CuratedTable.as_view(), name='curated_data'),
    path('autocomplete', views.autocomplete, name='autocomplete'),
    path('aviator-enable', views.api, name='api'),
    path('aviator-enabled', views.curated, name='curated'),
    path('curated_autocomplete', views.curated_autocomplete, name='curated_autocomplete'),
    path('aviator_api', views.aviator_api, name='aviator_api'),
]

webserver/main/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField, ArrayField
from djchoices import DjangoChoices, ChoiceItem

#Single Row table
class GlobalStatistics(models.Model):
    data_size = models.BigIntegerField()
    num_calls = models.BigIntegerField()
    weekdays_online = ArrayField(models.IntegerField(), default=list)
    weekdays_offline = ArrayField(models.IntegerField(), default=list)
    recovery_rate = ArrayField(models.IntegerField(), default=list)

class Publication(models.Model):
    title = models.TextField(db_index=True)
    abstract = models.TextField()
    authors = ArrayField(models.TextField(), blank=True, default=list)
    year = models.SmallIntegerField(db_index=True)
    journal = models.TextField(db_index=True)
    pubmed_id = models.CharField(max_length=50, unique=True, db_index=True)
    biotools_id = models.CharField(max_length=250, default="")
    user_kwds = ArrayField(models.TextField(null=True, blank=True), blank=True, default=list)
    mesh_terms = ArrayField(models.TextField(null=True, blank=True), blank=True, default=list)
    contact_mail = ArrayField(models.EmailField(null=True, blank=True), blank=True, default=list)
    url = ArrayField(models.TextField())


class WebsiteStatus(DjangoChoices):
    ONLINE = ChoiceItem("O")
    OFFLINE = ChoiceItem("F")
    TEMP_OFFLINE = ChoiceItem("T")
    UNKNOWN = ChoiceItem("U")


class Website(models.Model):
    original_url = models.TextField(db_index=True, unique=True)
    derived_url = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=WebsiteStatus.choices,
                              default=WebsiteStatus.UNKNOWN)
    papers = models.ManyToManyField(Publication, related_name='websites')
    ip = models.GenericIPAddressField(null=True)
    server = models.CharField(max_length=200)
    analytics = models.CharField(max_length=50)
    timezone = models.CharField(max_length=50)
    framework = models.CharField(max_length=50)
    script = models.CharField(max_length=50)
    certificate_secure = models.BooleanField()
    security_issuer = models.CharField(max_length=100)
    # store offline/online/NA per day in ascending date order
    states = ArrayField(models.BooleanField(null=True), default=list)
    percentage = models.FloatField(null=True, default=None)
    last_heap_size = models.IntegerField(default=0)


class WebsiteCall(models.Model):
    website = models.ForeignKey(Website, related_name='calls', on_delete=models.CASCADE)
    datetime = models.DateTimeField(db_index=True)
    ok = models.BooleanField()
    error = models.CharField(max_length=200)
    msg = models.TextField()
    code = models.IntegerField()
    json_data = JSONField()

    class Meta:
        indexes = [
            models.Index(fields=['datetime', 'website']),
        ]


class Tag(models.Model):
    name = models.CharField(max_length=50)


class CuratedWebsite(models.Model):
    title = models.CharField(max_length=200)
    pubmed_id = models.CharField(max_length=50, unique=True, db_index=True)
    year = models.SmallIntegerField(db_index=True)
    journal = models.TextField(db_index=True)
    description = models.TextField()
    authors = ArrayField(models.TextField(), blank=True, default=list)
    url = models.CharField(max_length=100)
    api_url = models.CharField(max_length=100)
    tags = models.ManyToManyField(Tag, related_name='curated')
    website = models.OneToOneField(Website, related_name='curated', on_delete=models.CASCADE)
    status = models.CharField(max_length=1, choices=WebsiteStatus.choices,
                              default=WebsiteStatus.UNKNOWN)
    dates = ArrayField(models.DateTimeField(), default=list)
    # store offline/online/NA per day in ascending date order
    states = ArrayField(models.BooleanField(null=True), default=list)
    percentage = models.FloatField(null=True, default=None)
    contact_mail = models.EmailField(null=True, blank=True)
    days_reminder = models.IntegerField(default=0)

webserver/main/forms.py
from django import forms
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox


class CaptchaForm(forms.Form):
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())

webserver/main/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.cache import cache_page
from django.utils.cache import add_never_cache_headers
from .models import Website, WebsiteCall, Publication, Tag, CuratedWebsite, GlobalStatistics
from datetime import timedelta
import json
from django.contrib.postgres.aggregates import ArrayAgg, BoolOr
from django.db.models import Q, BooleanField
from cache_memoize import cache_memoize
from django.conf import settings
from django_datatables_view.base_datatable_view import BaseDatatableView
from .stats import get_index_stats, get_all_statistics
import csv
from .forms import CaptchaForm


def filter_queryset(qs, filter_col2v, colnames, email_field):
    numeric_fields = {"year"}
    bool_agg_fields = {"ssl": "websites__certificate_secure"}
    if hasattr(qs.model, "websites"):
        numeric_agg_field = {"percentage": "websites__percentage"}
    elif hasattr(qs.model, "website"):
        numeric_agg_field = {"percentage": "website__percentage"}
    else:
        numeric_agg_field = {}
    qs_filter = {}
    for col, v in filter_col2v.items():
        field_name = colnames[col]
        if field_name in email_field:
            v = v.replace("[at]", "@")
        if field_name in bool_agg_fields:
            agg_filter = {}
            agg_filter["{}__gte".format(bool_agg_fields[field_name])] = v == 'true'
            annot_addition = {
                "{}_filter".format(field_name): BoolOr(Q(**agg_filter),
                                                       output_field=BooleanField())
            }
            qs = qs.annotate(**annot_addition)
            qs_filter["{}_filter".format(field_name)] = True
        elif field_name in numeric_fields:
            min_str, max_str = v.split(';')
            if min_str and max_str:
                qs_filter["{}__range".format(field_name)] = (float(min_str), float(max_str))
            elif min_str:
                qs_filter["{}__gte".format(field_name)] = float(min_str)
            elif max_str:
                qs_filter["{}__lte".format(field_name)] = float(max_str)
        elif field_name in numeric_agg_field:
            min_str, max_str = v.split(';')
            if min_str or max_str:
                agg_filter = {}
                if min_str and max_str:
                    agg_filter["{}__range".format(numeric_agg_field[field_name])] = (
                        float(min_str), float(max_str))
                elif min_str:
                    agg_filter["{}__gte".format(numeric_agg_field[field_name])] = float(min_str)
                elif max_str:
                    agg_filter["{}__lte".format(numeric_agg_field[field_name])] = float(max_str)
                annot_addition = {
                    "{}_filter".format(field_name): BoolOr(Q(**agg_filter),
                                                           output_field=BooleanField())
                }
                qs = qs.annotate(**annot_addition)
                qs_filter["{}_filter".format(field_name)] = True
        else:
            qs_filter["{}__icontains".format(field_name)] = v
    if qs_filter:
        qs = qs.filter(**qs_filter)
    return qs


def prepare_csv_export(qs, columns, header, request, email_fields, ignore_fields, name):
    response = HttpResponse(content_type='text/csv')
    writer = csv.writer(response, delimiter=',')
    header_line = []
    shown = []
    if "columns" in request.POST:
        shown = request.POST["columns"].split(';')
    for k in range(0, len(columns)):
        if str(k) in shown and (columns[k] not in ignore_fields):
            header_line.append(header[k])
    writer.writerow(header_line)

    filter_col2v = {k: request.POST[str(k)] for k in range(0, len(columns)) if
                    str(k) in shown and (columns[k] not in ignore_fields) and request.POST[str(k)] not in {"", ";"}}
    qs = filter_queryset(qs, filter_col2v, columns, email_fields)

    csv_content = []
    for k in range(0, len(columns)):
        if str(k) in shown and (columns[k] not in ignore_fields):
            field_name = columns[k]
            values = qs.values_list(field_name)
            if field_name in email_fields:
                new_values = []
                for i in range(0, len(values)):
                    new_value = []
                    for j in range(0, len(values[i][0])):
                        new_value.append(str(values[i][0][j]).replace("@", "[at]"))
                    new_values.append(str(new_value))
                csv_content.append(new_values)
            else:
                csv_content.append([x[0] for x in values])
    writer.writerows(list(map(list, zip(*csv_content))))
    response['Content-Disposition'] = 'attachment; filename="aviator_' + name + '.csv"'
    return response


def index(request):
    context = get_index_stats()
    context['overall_calls'] = 0
    context['overall_size'] = 0
    for gs in GlobalStatistics.objects.all():
        context['overall_calls'] = "{:,}".format(gs.num_calls)
        context['overall_size'] = "{:,}".format(gs.data_size // 1000000000)
    return render(request, 'index.html', context)


def help(request):
    return render(request, 'help.html')


def overview(request):
    context = {'search_column': 0, 'search_string': ''}
    if request.method == 'POST':
        context['search_column'] = request.POST['search_column']
        context['search_string'] = request.POST['search_string']
    return render(request, 'overview.html', context)


@cache_memoize(settings.CACHE_TIMEOUT)
def get_publication_datatable_info():
    context = {}
    context["websites"] = json.dumps({x['pk']: x for x in list(
        Website.objects.all().values('pk', 'status', 'original_url', 'derived_url', 'percentage',
                                     'states'))})
    return context


def publications(request):
    if request.POST and 'search_column' not in request.POST:
        form = CaptchaForm(request.POST)
        if form.is_valid():
            qs = Publication.objects.all().prefetch_related('websites').annotate(
                status=ArrayAgg('websites__status'), percentage=ArrayAgg('websites__percentage'),
                original_url=ArrayAgg('websites__original_url'),
                derived_url=ArrayAgg('websites__derived_url'), scripts=ArrayAgg('websites__script'),
                ssl=ArrayAgg('websites__certificate_secure'),
                heap_size=ArrayAgg('websites__last_heap_size'),
                website_pks=ArrayAgg('websites__pk'))
            columns = ['title', 'status', 'percentage', 'authors', 'year', 'journal', 'pubmed_id', 'biotools_id',
                       'abstract', 'original_url', 'derived_url', 'contact_mail', 'user_kwds',
                       'scripts', 'ssl', 'heap_size', 'website_pks']
            header = ['Publication Title', 'Status', 'Last 30 days', 'Authors', 'Year', 'Journal', 'PubMed ID', 'bio.tools ID',
                      'Abstract',
                      'Original URL', 'Derived URL', 'Contact E-Mail', 'Keywords',
                      'Programming Languages', 'SSL', 'RAM Usage', 'Details']
            email_fields = {"contact_mail"}
            ignore_fields = {"website_pks"}
            return prepare_csv_export(qs, columns, header, request, email_fields,
                                      ignore_fields, "publications")
        else:
            return HttpResponse("Wrong Captcha")
    else:
        form = CaptchaForm()
    context = {'search_column': -1, 'search_string': '', 'form': form}
    if request.method == 'POST' and 'search_column' in request.POST:
        context['search_column'] = request.POST['search_column']
        context['search_string'] = request.POST['search_string']
    if request.method == 'GET' and 'search_column' in request.GET:
        context['search_column'] = request.GET['search_column']
        context['search_string'] = request.GET['search_string']
    return render(request, 'publications.html', context)


def curated(request):
    if request.POST and 'search_column' not in request.POST:
        form = CaptchaForm(request.POST)
        if form.is_valid():
            columns = ['title', 'status', 'percentage', 'authors', 'year', 'journal', 'pubmed_id',
                       'description', 'url', 'tag_tags', 'website']
            header = ['Tool', 'Status', 'Last 30 days', 'Authors', 'Year', 'Journal', 'PubMed ID',
                      'Description', 'URL', 'Keywords', 'Website Details']
            qs = CuratedWebsite.objects.all().prefetch_related('tags').annotate(
                tag_tags=ArrayAgg('tags__name'))
            email_fields = {}
            ignore_fields = {"website"}
            return prepare_csv_export(qs, columns, header, request, email_fields,
                                      ignore_fields, "curated")
        else:
            return HttpResponse("Wrong Captcha")
    else:
        form = CaptchaForm()
    context = {'search_column': -1, 'search_string': '', 'form': form}
    if request.method == 'POST' and 'search_column' in request.POST:
        context['search_column'] = request.POST['search_column']
        context['search_string'] = request.POST['search_string']
    if request.method == 'GET' and 'search_column' in request.GET:
        context['search_column'] = request.GET['search_column']
        context['search_string'] = request.GET['search_string']
    return render(request, 'curated.html', context)


def details(request, pk):
    context = {}
    website = get_object_or_404(Website, pk=pk)
    show_for_x_days = 30
    latest_time = website.calls.latest("datetime").datetime
    first_call = website.calls.earliest("datetime").datetime
    context['calls'] = website.calls.filter(datetime__date__gte=latest_time-timedelta(days=show_for_x_days)).order_by('-datetime')
    context['website'] = website
    context["first_call"] = first_call
    return render(request, 'details.html', context)

webserver/main/templates/author.html
<!DOCTYPE html>
{% load staticfiles %}
{% url 'main:details' as details %}
<html  lang="en">
	<head>
    <meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <title>Aviator</title>
    {% load compress %}
    {% compress css inline %}
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/aviator.css' %}" rel="stylesheet" type="text/css">
    {% endcompress %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
	
    {% compress js inline %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endcompress %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
  </head>
	<body>
    {% include "navbar.html" %} <div class="contact-container">
      <form>
        <div class="form-group">
          <label for="input_name">Name</label>
          <input type="text" class="form-control" id="input_name" placeholder="Name">
        </div>
        <div class="form-group">
          <label for="input_email">Email address</label>
          <input type="email" class="form-control" id="input_email" placeholder="name@example.com">
        </div>
        <br>
        <div class="form-group">
          <label for="input_pubmed">PubMed ID</label>
          <input type="text" class="form-control" id="input_pubmed" placeholder="PubMed ID">
        </div>
        <div class="form-group">
          <label for="input_toolname">Tool Name</label>
          <input type="text" class="form-control" id="input_toolname" placeholder="Tool Name">
        </div>
        <div class="form-group">
          <label for="input_authors">Authors</label>
          <textarea class="form-control" id="input_authors" rows="2" placeholder="Authors"></textarea>
        </div>
        <div class="form-group">
          <label for="input_url">Tool URL</label>
          <input type="text" class="form-control" id="input_url" placeholder="URL">
        </div>
        <br>
        <div class="form-group">
          <label for="api_url">API URL</label><br>
          <label for="api_url">Add an api link to your webpage for consistent on-/offline validation (<a href="{% url 'main:api'%}">see here</a>)</label>
          <input type="text" class="form-control" id="api_url" placeholder="API URL">
        </div>
        <br>
        <div class="form-group">
          <label for="input_tooldesc">Description</label>
          <textarea class="form-control" id="input_tooldesc" rows="5" placeholder="Description"></textarea>
        </div>
        <div class="form-group">
          <label for="input_tags">Tags</label>
          <select multiple class="selectpicker form-control" id="input_tags" data-live-search="true">
          {% for tag in tags %}
            <option>{{ tag.name }}</option>
          {% endfor %}
          </select>
        </div>
        <br>
        <div class="form-group">
          <label for="input_comments">Comments</label>
          <textarea class="form-control" id="input_comments" rows="5" placeholder="Comments"></textarea>
        </div>
        <br>
        <div class="custom-control custom-checkbox mb-3">
          <input type="checkbox" class="custom-control-input" id="messageValidation">
          <label class="custom-control-label" for="messageValidation">I want to get an automated message to the given email address, if the website is down for more than <input type="number" id="days_reminder" name="days_reminder" min="1" max="28" value="3" width="2"> days.</label>
        </div>
        <br>
        <a id="sendmail" target="_blank" rel="noopener" class="btn btn-outline-light" href="mailto:aviator.ccb@gmail.com" onclick="prepareEmail()">Send email</a>
      </form>
  </div>
	</body>
</html>
<script>
  function prepareEmail() {
    var text = "Name: "+document.getElementById("input_name").value + "\r\n";
    text += "Email: "+document.getElementById("input_email").value + "\r\n\r\n";
    text += "Tool: "+document.getElementById("input_toolname").value + "\r\n";
    text += "PubMed ID: "+document.getElementById("input_pubmed").value + "\r\n";
    text += "URL: "+document.getElementById("input_url").value + "\r\n";
    text += "API: "+document.getElementById("api_url").value + "\r\n";
    text += "Authors: " + document.getElementById("input_authors").value + "\r\n";
    text += "Description: " + document.getElementById("input_tooldesc").value + "\r\n";
    text += "Tags: "+document.getElementsByClassName("filter-option-inner-inner")[0].innerHTML + "\r\n\r\n";
    text += "Comments: "+document.getElementById("input_comments").value + "\r\n";
    text += "I want to be informed, if the website is down: "+ (document.getElementById("messageValidation").checked ? "Yes" : "No") + "\r\n";
    text += "Days before reminder: "+ (document.getElementById("days_reminder").value) + "\r\n";

    text = encodeURIComponent(text)

    document.getElementById("sendmail").href = `mailto:aviator.ccb@gmail.com?subject=${document.getElementById("input_pubmed").value}&body=${text}`
    return true;
  }
</script>

webserver/main/templates/navbar.html
{% load static %}

{% url 'main:index' as index %}
{% url 'main:overview' as overview %}
{% url 'main:publications' as publications %}
{% url 'main:author' as author %}
{% url 'main:statistics' as statistics %}
{% url 'main:api' as api %}
{% url 'main:help' as help %}
{% url 'main:curated' as curated %}

<script type="text/javascript" src="https://ccb-web.cs.uni-saarland.de/epica/epica.js"
        data-site_id="46"
        data-site_type="Tool"></script>
<noscript>
  <p><img src="//epica.cs.uni-saarland.de/matomo.php?idsite=37&amp;rec=1" style="border:0;" alt=""/>
  </p>
  <p><img src="//epica.cs.uni-saarland.de/matomo.php?idsite=38>&amp;rec=1" style="border:0;"
          alt=""/></p>
</noscript>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ index }}"><img src="{% static 'images/aviator_logo_black_font.svg' %}" alt="Aviator" height="35px" style="margin-top: -10px"> Aviator</a>
  <div class="navbar-login-container" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == index %}active{% endif %}">
        <a class="nav-link" href="{{ index }}"><i class="fas fa-home"></i> Home</a>
      </li>
      <li class="nav-item {% if request.path == publications %}active{% endif %}">
        <a class="nav-link" href="{{ publications }}"><i class="fas fa-table"></i> Tool List</a>
      </li>
      <li class="nav-item {% if request.path == curated %}active{% endif %}">
        <a class="nav-link" href="{{ curated }}"><i class="fas fa-tools"></i> Aviator-enabled</a>
      </li>
      <li class="nav-item {% if request.path == author %}active{% endif %}">
        <a class="nav-link" href="{{ author }}"><i class="fas fa-paper-plane"></i> Register</a>
      </li>
      <li class="nav-item {% if request.path == statistics %}active{% endif %}">
        <a class="nav-link" href="{{ statistics }}"><i class="fas fa-chart-bar"></i> Statistics</a>
      </li>
      <li class="nav-item {% if request.path == api %}active{% endif %}">
        <a class="nav-link" href="{{ api }}"><i class="fas fa-cloud"></i> How to Aviator-enable my tool</a>
      </li>
      <li class="nav-item {% if request.path == help %}active{% endif %}">
        <a class="nav-link" href="{{ help }}"><i class="fas fa-info-circle"></i> Help</a>
      </li>
    </ul>
    <form id="nav_search_form" class="form-inline my-2 my-lg-0"
          action="{% url 'main:publications' %}" method="post">
      {% csrf_token %}
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="ddBtnN"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Title&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </button>
        <div class="dropdown-menu" aria-labelledby="ddBtn1">
          <a class="dropdown-item"
             onclick="document.getElementById('ddBtnN').innerHTML = this.innerHTML;document.getElementById('search_column').value = 0;return false;">Title&nbsp;&nbsp;&nbsp;&nbsp;</a>
          <a class="dropdown-item"
             onclick="document.getElementById('ddBtnN').innerHTML = this.innerHTML;document.getElementById('search_column').value = 3;return false;">Authors&nbsp;&nbsp;</a>
          <a class="dropdown-item"
             onclick="document.getElementById('ddBtnN').innerHTML = this.innerHTML;document.getElementById('search_column').value = 5;return false;">Journal&nbsp;&nbsp;</a>
          <a class="dropdown-item"
             onclick="document.getElementById('ddBtnN').innerHTML = this.innerHTML;document.getElementById('search_column').value = 6;return false;">PubMed
            ID&nbsp;&nbsp;</a>
          <a class="dropdown-item"
             onclick="document.getElementById('ddBtnN').innerHTML = this.innerHTML;document.getElementById('search_column').value = 7;return false;">bio.tools
             ID&nbsp;&nbsp;</a>
          <a class="dropdown-item"
             onclick="document.getElementById('ddBtnN').innerHTML = this.innerHTML;document.getElementById('search_column').value = 8;return false;">Abstract&nbsp;&nbsp;</a>
          <a class="dropdown-item"
             onclick="document.getElementById('ddBtnN').innerHTML = this.innerHTML;document.getElementById('search_column').value = 9;return false;">Original
            URL</a>
            <a class="dropdown-item"
               onclick="document.getElementById('ddBtnN').innerHTML = this.innerHTML;document.getElementById('search_column').value = 10;return false;">Derived
              URL</a>
        </div>
      </div>&nbsp;&nbsp;&nbsp;
      <input id="search_column" name="search_column" class="form-control mr-sm-2" type="hidden"
             placeholder="Search" aria-label="Search" value="0">
      <input id="nav_search" name="search_string" class="form-control mr-sm-2" type="search"
             placeholder="Search" aria-label="Search">
      <button id="nav_search_btn" class="btn btn-outline-light my-2 my-sm-0" type="submit"
              onclick=""><i class="fas fa-search"></i> Search
      </button>
      <div>
        <a href="https://www.ccb.uni-saarland.de/" target="_blank" rel="noopener">
          <img src="{% static 'images/logo_ccb_white_h80.png' %}"
               alt="Chair for Clinical Bioinformatics" hspace="10"
               style="width:83px;height:40px;border:0;">
        </a>
      </div>
      <div>
        <a href="https://www.uni-saarland.de/en/home.html" target="_blank" rel="noopener">
          <img src="{% static 'images/logo_uds_white_h80.png' %}"
               alt="University of Saarland, Germany" hspace="10"
               style="width:100px;height:40px;border:0;">
        </a>
      </div>
      <div>
        <a href="https://www.bihealth.org/de/forschung/arbeitsgruppen/dominik-seelow" target="_blank" rel="noopener">
          <img src="{% static 'images/logo_bihealth.png' %}"
               alt="Berlin Institute of Health" hspace="10"
               style="width:163px;height:40px;border:0;">
        </a>
      </div>
    </form>
  </div>
</nav>

<script>
  $(document).ready(function () {
    function createNavbarSearchData() {
      data = {};
      data[$('#search_column').val()] = $('#nav_search').val();
      data["q"] = $('#search_column').val();
      return data;
    }

    $(function () {
      $("#nav_search").autocomplete({
        source: function (request, response) {
          $.getJSON("{% url 'main:autocomplete' %}", createNavbarSearchData(), response);
        },
        minLength: 1
      });
      if ($("#nav_search").autocomplete().data("ui-autocomplete") != undefined) {
        $("#nav_search").autocomplete().data("ui-autocomplete")._renderItem = function (ul, item) {
          var newText = String(item.value).replace(
                  new RegExp(this.term, "gi"),
                  "<span style='color: white;'><strong>$&</strong></span>");
          return $("<li></li>")
                  .data("item.autocomplete", item)
                  .append("<div>" + newText + "</div>")
                  .appendTo(ul);
        };
      }
    });

    $("#nav_search_btn").click(function () {
      // disable button
      $(this).prop("disabled", true);
      // add spinner to button
      $(this).html(`<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> `);

      // submit after 1 sec
      setTimeout(function () {
        $('#nav_search_form').submit();
      }, 1000)
    })
  })
</script>